# Start from the latest Alpine image
FROM alpine:3.19

# Update the system
RUN apk update && apk upgrade

# Install ansible
RUN apk add --no-cache go

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run the command when the container launches
CMD ["sh"]