# Start from the latest Alpine image
FROM alpine:3

ENV TERRAFORM_VERSION 1.7.1

# Update the system
RUN apk update && apk upgrade

# Install curl and other dependencies
RUN apk add --no-cache curl tar unzip

# Install terraform
RUN cd /usr/local/bin && \
    curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run the command when the container launches
CMD ["sh"]