# Start from the specified Alpine image
FROM alpine:3.20.1

# Update the system
RUN apk update && apk upgrade

# Install curl and other dependencies
RUN apk add --no-cache curl tar

# Install kubectl
RUN apk add --no-cache kubectl

# Install Helm
RUN apk add --no-cache helm   

# Install k9s
RUN apk add --no-cache k9s

# Install Flux CLI
RUN curl -o /tmp/flux.tar.gz -sLO https://github.com/fluxcd/flux2/releases/download/v2.3.0/flux_2.3.0_linux_amd64.tar.gz \
    && tar -C /tmp/ -zxvf /tmp/flux.tar.gz \
    && mv /tmp/flux /usr/local/bin/flux \
    && chmod +x /usr/local/bin/flux

# Run the command when the container launches
CMD ["sh"]