# Start from the latest Alpine image
FROM alpine:latest

# Update the system
RUN apk update && apk upgrade

# Install ansible
RUN apk add --no-cache ansible

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the command when the container launches
CMD ["sh"]