name: Kube-Tools Docker Image CI

on:
  push:
    paths:
      - 'kube-tools/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'kube-tools/**'
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install jq
      run: sudo apt-get install jq
    - name: Read Alpine version
      id: alpine
      run: echo "::set-output name=version::$(jq -r .alpine_version kube-tools/config.json)"
    - name: Build the Docker image
      run: docker build . --file kube-tools/Dockerfile --build-arg ALPINE_VERSION=${{ steps.alpine.outputs.version }} --tag kube-tools:v0.${{ github.run_number }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'kube-tools:v0.${{ github.run_number }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif' 
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/kube-tools:v0.${{ github.run_number }}
    
